language: node_js
node_js:
 - "stable"

cache:
  yarn: true
  directories:
  - node_modules

before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash
 - export PATH=$HOME/.yarn/bin:$PATH
 - cd functions

install:
 - yarn

before_script:
 - cd functions

script:
 - npm run build
 - npm run deploy -- --token $FIREBASE_TOKEN
